.PHONY: clean All

All:
	@echo "----------Building project:[ UOC20241 - Debug ]----------"
	@"$(MAKE)" -f  "UOC20241.mk"
clean:
	@echo "----------Cleaning project:[ UOC20241 - Debug ]----------"
	@"$(MAKE)" -f  "UOC20241.mk" clean
